### ISSUE TITLE
Re-instate GOsa² 2.6 uid-from-fullname generation

### ISSUE THREAD

**Issue by sunweaver** [gosa-project/gosa-core#5]
In Debian Edu, we found that the UID generation code in gosa 2.7 is so much different from 2.6 (and it seemed it actually is buggy), that we put some effort into imitating the 2.6'ish style of UID generation.

Does this make sense for GOsa 2.7? Maybe controlled by some gosa.conf option?

```
Description: Re-instate GOsa² 2.6 uid-from-fullname generation
Author: Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Abstract:
 For details, see http://bugs.debian.org/793455

--- a/gosa-core/include/functions.inc
+++ b/gosa-core/include/functions.inc
@@ -3815,7 +3815,7 @@
     foreach($matches as $match){

         // No start position given, then add the complete value
-        if(!isset($match[5])){
+        if(!isset($match[7])){
             $replacements[$match[0]][] = $attributes[$match[2]];

         // Start given but no end, so just add a single character
@@ -3831,10 +3831,16 @@
             for($i=$match[5]; $i<= $match[7]; $i++){
                 if(isset($attributes[$match[2]][$i])){
                     $tmp = " ".$attributes[$match[2]];
-                    $str .= $tmp[$i];
+                    $str = substr ($tmp, 1, $i);
                     $replacements[$match[0]][] = trim($str);
                 }
             }
+
+            // if a given attribute's value is shorter than required, use the
+            // full length of the attribute's value
+            if (!$replacements[$match[0]]) {
+                $replacements[$match[0]][] = $attributes[$match[2]];
+            }
         }
     }
```

**Comment by master-caster** [comment]
>        if(!isset($match[7])){

It looks like a bug to me since the code allows to apply the starting position only but not to specify just
the ending position. The starting position can't be in the same place with the ending position.
Using
>        if(!isset($match[5])){

is the way to go here.

This code snipets
<pre>
-                    $str .= $tmp[$i];
+                    $str = substr ($tmp, 1, $i);
</pre>
do different things. The first just reads one character the second reads the whole string
starting at index 1 (so we start with the second character).

That ends up with two completely different arrays.
Defining a rule like this __%givenName[5-9]__ it is more intuitive for
me, to get just characters between and included the given postitions while
the old implementation will create an array consisting of all values starting
at index 1 to the start position up to values starting at index 1 to the end position. 

example:
<pre>
$givenName = "tester123"
$rule = {$givenName[2-4]}

</pre>

old implementation:
1. es
2. est
3. este

new implementation:
1. s
2. st
3. ste


The third part of this patch, using the whole value if the desired positions are out
of range, should be discussed. In my opinion it is correct to return an empty
array if the applied rule doesn't match.

If you get no return values you need to modify your rule.

But considering surnames with only two letters i do understand the use
of this exception.

**Comment by master-caster** [comment]
The uid generation has been reverted.
